# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'staff'
    label: 'Staff'
    folder: '_staff_members/'
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}


name: Anna Thompson
position: Marketing
image_path: https://source.unsplash.com/collection/139386/601x601?a=.png
twitter: CloudCannonApp
blurb: Anna likes long walks on the beach and buffet breakfast.